# Generated by Django 3.1 on 2022-02-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sex', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sex.sex'),
        ),
    ]
