# Generated by Django 3.1 on 2022-02-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_name', models.CharField(max_length=10, unique=True)),
                ('slug', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
