# Generated by Django 3.1 on 2022-02-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sex',
            name='slug',
        ),
    ]
